import './globals.css';

export const metadata = {
  title: 'Next.js App with Tailwind',
  description: 'Generated by Next.js, styled with Tailwind CSS',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className="dark">
      <head>
        {/* Next.js automatically manages other head elements based on metadata and page content */}
        {/* You can add additional global <meta>, <link>, etc. tags here if specifically needed */}
      </head>
      <body style={{ overscrollBehaviorX: "auto" }}>{children}</body>
    </html>
  );
}
